### ISSUE TITLE
Questions/0019.php solution discussion

### ISSUE THREAD

**Issue by AronNovak** [basselin/php-certification-training#1]
I think only option3 can be the right choice, see this:

```
<?php
$a = new stdClass();
$b = $a;
print serialize($a === $b);
print serialize($a instanceof $b);
print "\n";
$a = new stdClass();
$b = clone $a;
print serialize($a === $b);
print serialize($a instanceof $b);
```

Result:
b:1;b:1;
b:0;b:1;

So instanceof is for a different purpose, is just to determine whether a PHP variable is an instantiated object of a certain class.

**Comment by basselin** [comment]
Your right ! Thanks
